### ISSUE TITLE
Allow analysis of single models with create_APCsummary and plot_jointMarginalAPCeffects

### ISSUE THREAD

**Issue by MaxWeigert** [bauer-alex/APCtools#13]
Currently, both function require a list of regression models. If there is only a single model, the input should not necessarily be a list.

**Comment by bauer-alex** [comment]
Do you have a concrete idea of how to handle it differently?
All options I can think of would actually double the documentation and would accordingly also be somewhat unintuitive.

**Comment by MaxWeigert** [comment]
I would check if the input is either a list of models or a single gam model object. After this, my idea would be to convert the single model into a list and leave everything as it currently is. In the documentation, we would only need to add that model_list could also be a single model. Does this make sense? 

Let me know if you fine with that approach and I'll implement that.

**Comment by bauer-alex** [comment]
Makes sense! I just thought too complicated. Will implement it and close the issue.
