### ISSUE TITLE
plot_marginalAPCeffects with variables conversions in model formula

### ISSUE THREAD

**Issue by MaxWeigert** [bauer-alex/APCtools#14]
plot_marginalAPCeffects cannot handle models where a variable is converted in the model formula (e.g. through as.factor), and throws out an error. plot_smoothEffects and plot_linearEffects do not have this kind of problem.

**Comment by bauer-alex** [comment]
Do you have a minimal reproducible example for this?

**Comment by MaxWeigert** [comment]
`library(APCtools)
library(mgcv)
data(travel)

# Model formula with conversion:
travel$residence_region <- as.character(travel$residence_region)
model <- gam(mainTrip_distance ~ te(age, period) + as.factor(residence_region) +
               household_size + s(household_income), data = travel)
plot_marginalAPCeffects(model, dat = travel, variable = "age")
plot_linearEffects(model)

# Model formula without conversion:
travel$residence_region <- as.factor(travel$residence_region)
model2 <- gam(mainTrip_distance ~ te(age, period) + residence_region +
               household_size + s(household_income), data = travel)
plot_marginalAPCeffects(model2, dat = travel, variable = "age")
plot_linearEffects(model2)`

**Comment by MaxWeigert** [comment]
@bauer-alex I fixed this issue by removing the text outside the brackets. If this ok for you, please close the issue.
