### ISSUE TITLE
Confidence intervals for odds ratios

### ISSUE THREAD

**Issue by MaxWeigert** [bauer-alex/APCtools#15]
@bauer-alex I am currently working on several application cases of logistic regression for which I want to use our package to plot estimated effects on odds level. That let me think (and doubt) about our computation of the confidence intervals via the Delta method which may lead to negative or extremely small values. With this method, you construct symmetric intervals on odds level, but in my opinion this does not really make sense for regression models as hypothesis tests are performed on linear predictor level (see https://stats.stackexchange.com/questions/163824/different-ways-to-produce-a-confidence-interval-for-odds-ratio-from-logistic-reg, https://www.r-bloggers.com/2018/01/delta-method-standard-errors/). In an extreme case, the significance of the effects according to model output could be different from the significance according to the confidence interval. We had that in one particular case for a p value of  0.048.

An alternative method matching the model output is to simply exponentiate the boundaries of the interval. I would actually propose to implement this as a second (and possibly default) option for logit and log links. What do you think?

**Comment by bauer-alex** [comment]
Sounds good to me!

**Comment by bauer-alex** [comment]
In the above commit on the [issue-15](https://github.com/bauer-alex/APCtools/tree/issue-15) branch I implemented such a first functionality in `extract_summary_linearEffects`. Is that what you aimed for?

Sidenote: We should not forget about unit tests and re-rendering the vignettes, after making this the new default.

**Comment by bauer-alex** [comment]
1. The above commit also implements in in `plot_1Dsmooth`
2. I by accident commited both above changes in the main branch... So let's just keep it there and work on this issue quickly. I deleted branch `issue-15` again.

**Comment by MaxWeigert** [comment]
That's exactly what I aimed for. I can have some closer look at the beginning of next week.
