### ISSUE TITLE
Missing summary in software paper

### ISSUE THREAD

**Issue by strengejacke** [bauer-alex/APCtools#6]
Related to https://github.com/openjournals/joss-reviews/issues/4056

Please add a short summary to the paper, providing a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience.

**Comment by bauer-alex** [comment]
We now edited the introduction of the paper accordingly, to outline the general problem and the functionality of the package in more high-level form.
I hope this fits your request?
