### ISSUE TITLE
Minor additions to the manuscript

### ISSUE THREAD

**Issue by jaybee84** [bauer-alex/APCtools#8]
related to https://github.com/openjournals/joss-reviews/issues/4056

1. Statement of need : Please add in a bit more information about `identification problem` in the statement of need.
2. Is it possible to add a citation for `German Reiseanalyse survey– a repeated crosssectional study comprising information on German travelers between 1971 and 2018`

**Comment by bauer-alex** [comment]
@jaybee84 We now added the citation for the Reiseanalyse (see the _Forschungsgemeinschaft Urlaub und Reisen e.V._ citation).

Regarding the statement of need, we added a few more sentences to make the identification problem a bit clearer.
The previous version was:
> The critical challenge in APC analysis is the linear dependency of the components age, period, and cohort (cohort = period - age). Flexible methods and visualization techniques are needed to circumvent this *identification problem*.

And the new version is:
> The critical challenge in APC analysis is to deal with the perfect linear dependency of the components age, period, and cohort (cohort = period - age). As of this *identification problem*, the estimation of a linear regression model with all three components as individual main effects is only possible when imposing additional constraints in the estimation process, like restricting one main effect to zero [@yang_land_2013]. Such explicit constraints, however, typically result in effect structures that are hard to interpret. Accordingly, flexible methods and visualization techniques are needed that rely on less restrictive assumptions to circumvent the identification problem.

**Comment by bauer-alex** [comment]
Ah ok, makes sense.

Here our new proposal:
> The critical challenge in APC analysis is to deal with the perfect linear dependency of the components age, period, and cohort (cohort = period - age). `Due to this *identification problem*, inferring on the actual drivers behind observed temporal developments is difficult. For example, changes in recent years could be explained by developments related to the period, or by the fact that the respective observations only comprise later cohorts.` The estimation of a linear regression model with all three components as individual main effects is only possible when imposing additional constraints in the estimation process, like restricting one main effect to zero [@yang_land_2013]. Such explicit constraints, however, typically result in effect structures that are hard to interpret. Accordingly, flexible methods and visualization techniques are needed that rely on less restrictive assumptions to circumvent the identification problem.

**Comment by jaybee84** [comment]
This looks good to me .. thanks for making the additions.

**Comment by jaybee84** [comment]
I just reopened the issue since the latest change has not been incorporated in the pdf article yet. Please feel free to close the issue once the new version of the document is generated.
